export const SET_NOTES = 'SET_NOTES';
export const CLEAR_NOTES = 'CLEAR_NOTES';
export const SET_LOOKUP_DATA = 'SET_LOOKUP_DATA';
export const SET_REALTIME_DATA = 'SET_REALTIME_DATA';

export const GET_STOP_LOOKUP = 'GET_STOP_LOOKUP';
export const GET_REALTIME_DATA = 'GET_REALTIME_DATA';
